/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AvatarsPanel: typeof import('./src/components/panels/AvatarsPanel.vue')['default']
    EditorPage: typeof import('./src/components/shared/EditorPage.vue')['default']
    EquipsPanel: typeof import('./src/components/panels/EquipsPanel.vue')['default']
    GameCard: typeof import('./src/components/shared/GameCard.vue')['default']
    HadalPanel: typeof import('./src/components/panels/HadalPanel.vue')['default']
    MainContent: typeof import('./src/components/layout/MainContent.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    PlayerPanel: typeof import('./src/components/panels/PlayerPanel.vue')['default']
    QuickLaunchPanel: typeof import('./src/components/panels/QuickLaunchPanel.vue')['default']
    RankDots: typeof import('./src/components/shared/RankDots.vue')['default']
    SearchBar: typeof import('./src/components/shared/SearchBar.vue')['default']
    SettingsPanel: typeof import('./src/components/panels/SettingsPanel.vue')['default']
    SetupPanel: typeof import('./src/components/panels/SetupPanel.vue')['default']
    ShortcutsPanel: typeof import('./src/components/panels/ShortcutsPanel.vue')['default']
    Sidebar: typeof import('./src/components/layout/Sidebar.vue')['default']
    SkeletonGrid: typeof import('./src/components/shared/SkeletonGrid.vue')['default']
    SkillGrid: typeof import('./src/components/shared/SkillGrid.vue')['default']
    StarRating: typeof import('./src/components/shared/StarRating.vue')['default']
    Stepper: typeof import('./src/components/shared/Stepper.vue')['default']
    TitleBar: typeof import('./src/components/layout/TitleBar.vue')['default']
    WeaponsPanel: typeof import('./src/components/panels/WeaponsPanel.vue')['default']
  }
}
